version: '3.7'
services:

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - inertia
      - mysql
    container_name: nginx
    networks:
      - ajk

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    container_name: laravel
    command: >
      sh -c "php artisan serve --host=0.0.0.0"
    networks:
      - ajk
  
  inertia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    container_name: inertia
    command: >
      sh -c "yarn dev --host=0.0.0.0"
    networks:
      - ajk

  mysql:
    image: mysql:latest
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - ajk

networks:
  ajk:
    driver: bridge
    
